CREATE TABLE `pick_colours` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`text` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `text uniq` (`text`)
);

INSERT INTO `pick_colours` (`text`) VALUES
	('aqua'),
	('aquamarine'),
	('azure'),
	('beige'),
	('bisque'),
	('black'),
	('blue'),
	('brown'),
	('chartreuse'),
	('chocolate'),
	('coral'),
	('crimson'),
	('cyan'),
	('dark blue'),
	('dark green'),
	('dark grey'),
	('dark khaki'),
	('dark magenta'),
	('dark orange'),
	('dark purple'),
	('dark red'),
	('dark slate'),
	('dark turquoise'),
	('dark violet'),
	('dark yellow'),
	('deep pink'),
	('floral white'),
	('forest green'),
	('fuchsia'),
	('ghost white'),
	('gold'),
	('grey'),
	('green yellow'),
	('green'),
	('hot pink'),
	('indigo'),
	('ivory'),
	('khaki'),
	('lavender'),
	('light blue'),
	('light brown'),
	('light green'),
	('light grey'),
	('light pink'),
	('light red'),
	('light yellow'),
	('lime green'),
	('lime'),
	('magenta'),
	('maroon'),
	('navy'),
	('olive'),
	('orange red'),
	('orange'),
	('orchid'),
	('pale green'),
	('pale turquoise'),
	('peru'),
	('pink'),
	('plum'),
	('purple'),
	('red'),
	('royal blue'),
	('seagreen'),
	('silver'),
	('sky blue'),
	('slate blue'),
	('slate grey'),
	('snow'),
	('spring green'),
	('steel blue'),
	('tan'),
	('teal'),
	('turquoise'),
	('violet'),
	('white'),
	('yellow'),
	('yellowgreen')
;
