CREATE TABLE `pick_foods` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`text` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `text uniq` (`text`)
);

INSERT INTO `pick_foods` (`text`) VALUES
	('abalone'),
	('absinthe'),
	('açaí'),
	('acorn'),
	('adzuki'),
	('agave'),
	('ajwain'),
	('akara'),
	('ale'),
	('all-bran'),
	('alligator'),
	('allspice'),
	('almond milk'),
	('almond'),
	('aloe vera'),
	('amanattō'),
	('amaranth'),
	('amaretto'),
	('ambrosia'),
	('anchovy'),
	('angel food'),
	('anise'),
	('aniseed'),
	('antelope'),
	('antipasto'),
	('anzac biscuit'),
	('appetiser'),
	('apple crisp'),
	('apple jam'),
	('apple'),
	('appleberry'),
	('apricot'),
	('arctic roll'),
	('arrowroot'),
	('arroz con gandules'),
	('arroz'),
	('artichoke'),
	('arugula'),
	('asparagus'),
	('aspen'),
	('assam'),
	('aubergine'),
	('avocado'),
	('bacon'),
	('bael'),
	('bagel'),
	('baguette'),
	('baked beans'),
	('baking'),
	('bakpia'),
	('balila'),
	('bamboo shoot'),
	('banana bread'),
	('banana cake'),
	('banana chip'),
	('banana'),
	('bandeja paisa'),
	('bánh mì'),
	('barbecue'),
	('barberry'),
	('barley water'),
	('barley'),
	('basil'),
	('basmati'),
	('basted egg'),
	('bavarian cream'),
	('bay laurel'),
	('bay leaf'),
	('bbq'),
	('bean chip'),
	('beaufort'),
	('béchamèl'),
	('beebalm'),
	('beech'),
	('beef noodle soup'),
	('beef'),
	('beer bread'),
	('beer soup'),
	('beer'),
	('beet'),
	('beetroot'),
	('bell pepper'),
	('benniseed'),
	('bergamot'),
	('better than sex cake'),
	('bhaat'),
	('bhang'),
	('bhatamaas'),
	('bhurji'),
	('bigilla'),
	('bilberry'),
	('bindae-tteok'),
	('bing'),
	('birnen bonen und speck'),
	('biscotti'),
	('biscuit'),
	('bison'),
	('bisque'),
	('bitter melon'),
	('bitterroot'),
	('black cardamom'),
	('black forest sponge'),
	('black rice'),
	('black tea'),
	('blackcurrant'),
	('blancmange'),
	('blé noir'),
	('blini'),
	('blood lime'),
	('blood orange'),
	('blossoms'),
	('blue tomato'),
	('blueberry'),
	('boar'),
	('bob chorba'),
	('bodi ko achar'),
	('boiled egg'),
	('bok choy'),
	('boldo'),
	('bologi'),
	('bologna'),
	('bolognese'),
	('borage'),
	('borracho'),
	('borscht'),
	('borth'),
	('bouillabaisse'),
	('bouillon'),
	('boule'),
	('bouneschlupp'),
	('bounty bar'),
	('bourbon'),
	('boysenberry'),
	('brambleberry'),
	('bran'),
	('bread roll'),
	('bread'),
	('breadfruit'),
	('breadnut'),
	('brie'),
	('brioche'),
	('brittle'),
	('broadbean'),
	('broccoli'),
	('brochette'),
	('brooklime'),
	('brown rice'),
	('brownie'),
	('brunswick stew'),
	('brussels sprouts'),
	('bubr kacang hijau'),
	('buckthorn'),
	('buckwheat'),
	('buffalo'),
	('bulghur'),
	('bulkie'),
	('bull'),
	('bun'),
	('burger'),
	('burnet'),
	('bush banana'),
	('butter tea'),
	('butter'),
	('buttermilk'),
	('butternut'),
	('butterscotch'),
	('button mushroom'),
	('cabbage'),
	('cacao'),
	('cake'),
	('calamari'),
	('calisson'),
	('callos'),
	('calypso'),
	('calzone'),
	('camel'),
	('camembert'),
	('canapé'),
	('candied peel'),
	('candlenut'),
	('candy cane'),
	('candy'),
	('cantal'),
	('cantaloupe'),
	('caparrones'),
	('caper'),
	('capra e fagioli'),
	('capsicum'),
	('carambola'),
	('caramel'),
	('caraway'),
	('carbonara'),
	('cardamom'),
	('cardoon'),
	('carob'),
	('carom'),
	('carp'),
	('carrot'),
	('cashews'),
	('casimiroa'),
	('cassava'),
	('casserole'),
	('cassia'),
	('cassod'),
	('cassoulet'),
	('cat'),
	('catfish'),
	('catjang'),
	('catnip'),
	('catsear'),
	('cattle'),
	('caudle'),
	('cauliflower'),
	('cayenne pepper'),
	('celery'),
	('celtuce'),
	('cereal bar'),
	('cereal'),
	('chai'),
	('chakli'),
	('chamois'),
	('champagne'),
	('champignon'),
	('chantilly'),
	('chapea'),
	('chapssal doughnut'),
	('chard'),
	('charlotte'),
	('chaya'),
	('chayote'),
	('cheddar'),
	('cheese roll'),
	('cheese'),
	('cheesecake'),
	('cheeseweed'),
	('cherimoya'),
	('cherry'),
	('chestnut'),
	('chia'),
	('chicken kiev'),
	('chicken'),
	('chickpea'),
	('chickweed'),
	('chicory'),
	('chiffon cake'),
	('chili con carne'),
	('chili'),
	('chipotle'),
	('chips'),
	('chives'),
	('chocolate bar'),
	('chocolate truffle'),
	('chocolate-chip cookie'),
	('chocolate'),
	('chole bhature'),
	('chow'),
	('christmas pudding'),
	('chrysanthemum'),
	('chupe'),
	('churros'),
	('chutney'),
	('ciabatta'),
	('cicer'),
	('cider'),
	('cilantro'),
	('cinnamon roll'),
	('cinnamon'),
	('citrange'),
	('citron'),
	('citrus'),
	('clafoutis'),
	('clam chodder'),
	('clam juice'),
	('clam'),
	('clementine cake'),
	('clementine'),
	('cloudberry'),
	('clove'),
	('clover'),
	('cluster fig'),
	('cobbler'),
	('coca'),
	('cocoa puffs'),
	('coconut cream'),
	('coconut milk'),
	('coconut'),
	('cocoplum'),
	('cod'),
	('coffee'),
	('cola bottles'),
	('colby'),
	('coleslaw'),
	('collard'),
	('comfit'),
	('comfrey'),
	('compote'),
	('comté'),
	('condiment'),
	('confectionery'),
	('congee'),
	('cookie'),
	('cordial'),
	('cordon bleu'),
	('coriander'),
	('corn dog'),
	('corn flakes'),
	('corn'),
	('cornbread'),
	('corncrake'),
	('cornichon'),
	('costmary'),
	('cottage cheese'),
	('cotton candy'),
	('coucougnette'),
	('courgette'),
	('couscous'),
	('cowboy beans'),
	('cowpea'),
	('crab'),
	('cracker'),
	('cranberry'),
	('crawfish'),
	('crayfish'),
	('cream cheese'),
	('cream of mushroom'),
	('cream pie'),
	('cream'),
	('crème anglaise'),
	('crème fraîche'),
	('crème patissière'),
	('crêpe'),
	('cress'),
	('creton'),
	('cricket'),
	('crocodile'),
	('croissant'),
	('croque-madame'),
	('croque-monsieur'),
	('crouton'),
	('crumble'),
	('crumpet'),
	('cubanelle'),
	('cucumber'),
	('cucurbita'),
	('cultured meat'),
	('cumin'),
	('cupcake'),
	('curd'),
	('currant'),
	('curry berry'),
	('curry'),
	('custard-apple'),
	('custard'),
	('dahlia'),
	('daidai'),
	('daiquiri'),
	('dairy'),
	('dal bhat'),
	('dal'),
	('dalcha'),
	('dandelion'),
	('danish blue'),
	('darjeeling'),
	('dark chocolate'),
	('dark tea'),
	('date shake'),
	('date'),
	('datil'),
	('daube'),
	('daylily'),
	('deadnettle'),
	('deer'),
	('delight'),
	('dessert'),
	('deviled egg'),
	('dewberry'),
	('digestive'),
	('dill'),
	('dilly beans'),
	('dim sum'),
	('dingo'),
	('dip'),
	('dog'),
	('dolphin'),
	('donkey'),
	('dosa'),
	('doughnut'),
	('douzhin'),
	('dove'),
	('dragée'),
	('dragon tongue'),
	('dragon’s breath'),
	('dragonfruit'),
	('dromedary'),
	('drumstick'),
	('duck'),
	('dulce de leche'),
	('dulse'),
	('dumpling'),
	('dundicut'),
	('durian'),
	('earthnut'),
	('éclair'),
	('edamame'),
	('egg nog'),
	('egg roll'),
	('egg waffle'),
	('egg'),
	('eggplant'),
	('eggs benedict'),
	('einkorn'),
	('elderberry'),
	('elderflower'),
	('elephant'),
	('elk'),
	('elm'),
	('emmer'),
	('emu'),
	('enchilada'),
	('endive'),
	('energy drink'),
	('ensete'),
	('escarole'),
	('espelette'),
	('espresso'),
	('essiac'),
	('esterházy torte'),
	('eton mess'),
	('ewa aganyin'),
	('fabes de la granja'),
	('fakon'),
	('fallow deer'),
	('far aux pruneaux'),
	('far'),
	('farfalle'),
	('farina'),
	('fasole cu cârnaţi'),
	('fat hen'),
	('fava bean'),
	('feijoa'),
	('feijoada'),
	('fennel'),
	('fenugreek'),
	('feta'),
	('fettuccine'),
	('fiddlehead'),
	('fig'),
	('financier'),
	('finger lime'),
	('fish and chips'),
	('fish'),
	('fishwort'),
	('flageolet'),
	('flan parisien'),
	('flan'),
	('flatbean'),
	('flatbread'),
	('flaugnarde'),
	('flounder'),
	('fondant'),
	('fonio'),
	('forbidden fruit'),
	('fortune cookie'),
	('fougasse'),
	('fowl'),
	('fox nut'),
	('fraise tagada'),
	('fraisier'),
	('frangipane'),
	('frejon'),
	('friand'),
	('fried camembert'),
	('fried chicken'),
	('fried egg'),
	('fried rice'),
	('fries'),
	('frijoles'),
	('frittata'),
	('fritter'),
	('frog cake'),
	('frog'),
	('fromage frais'),
	('frozen custard'),
	('frozen yogurt'),
	('fruit jam'),
	('fruit salad'),
	('fruitcake'),
	('fudge'),
	('ful medames'),
	('fusilli'),
	('galette'),
	('gallo pinto'),
	('game'),
	('garlic'),
	('garnacha'),
	('gâteau magique'),
	('gazpacho'),
	('geechee'),
	('gelato'),
	('genoise'),
	('gentian'),
	('ghee'),
	('gherkin'),
	('ghugni'),
	('gin'),
	('ginger'),
	('gingerbread man'),
	('gingerbread'),
	('ginkgo nut'),
	('ginseng'),
	('giraffe'),
	('gnocchi'),
	('goat cheese'),
	('goat milk'),
	('goji'),
	('good king henry'),
	('goose'),
	('gooseberry'),
	('goosefoot'),
	('goulash'),
	('gourd'),
	('grain'),
	('gram'),
	('granola'),
	('grape'),
	('grapefruit'),
	('grasshopper'),
	('gratin'),
	('gravy'),
	('green tea'),
	('greenbean'),
	('grits'),
	('groat'),
	('grog'),
	('groundnut'),
	('gruel'),
	('guacamole'),
	('guar'),
	('guava'),
	('guinea pig'),
	('guineafowl'),
	('gumbo'),
	('gummi bear'),
	('habanero'),
	('hackberry'),
	('haggis'),
	('hainan'),
	('halloumi'),
	('ham'),
	('hangi'),
	('hardykiwi'),
	('hare'),
	('harissa'),
	('hashbrown'),
	('hawkbit'),
	('hawthorn'),
	('hazelnut'),
	('heartnut'),
	('heavy cake'),
	('herbal tea'),
	('hermelín'),
	('herring'),
	('herve'),
	('hibiscus'),
	('hickory'),
	('hoe'),
	('höfðingi'),
	('holy basil'),
	('honey'),
	('honeyberry'),
	('honeydew melon'),
	('honeynut'),
	('honeysuckle'),
	('hong dou tang'),
	('hoppin john'),
	('horopito'),
	('horse gram'),
	('horse'),
	('horseradish'),
	('hot buttered rum'),
	('hot chocolate'),
	('hot cross bun'),
	('hot dog'),
	('hot lemonade'),
	('hot toddy'),
	('hotpot'),
	('huckleberry'),
	('hummus'),
	('ice cream'),
	('ice milk'),
	('iceberg'),
	('icing'),
	('impala'),
	('irish coffee'),
	('ironbark'),
	('jack-o-lantern'),
	('jackfruit'),
	('jaffa cakes'),
	('jalapeño'),
	('japonica'),
	('jasmine'),
	('jerusalem artichoke'),
	('juice'),
	('juniper'),
	('kabocha'),
	('kaffir lime'),
	('kaitaia fire'),
	('kalamata olive'),
	('kale'),
	('kalpi'),
	('kamokamo'),
	('kamut'),
	('kangaroo'),
	('karit'),
	('karuka'),
	('kava'),
	('kawakawa'),
	('kebab'),
	('kefir'),
	('kellogg’s'),
	('kernza'),
	('ketchup'),
	('key lime'),
	('kidney bean'),
	('kimchi'),
	('kitkat'),
	('kiwi'),
	('knotweed'),
	('kohlrabi'),
	('kōkihi'),
	('kola nut'),
	('komatsuna'),
	('koose'),
	('kouign-amann'),
	('kuka'),
	('kuli-kuli'),
	('kumara'),
	('kumquat'),
	('kurrat'),
	('l&p'),
	('lablab'),
	('lady finger'),
	('lamb'),
	('lamington'),
	('langoustine'),
	('langsat'),
	('lasagne'),
	('lassi'),
	('latka'),
	('laurel caraway'),
	('lavender'),
	('le puy'),
	('leek'),
	('legume'),
	('lemon balm'),
	('lemon basil'),
	('lemon cheese'),
	('lemon curd'),
	('lemon meringue pie'),
	('lemon thyme'),
	('lemon'),
	('lemonade'),
	('lemongrass'),
	('lentil'),
	('lettuce'),
	('licorice'),
	('lima bean'),
	('limburger'),
	('lime'),
	('limeade'),
	('limeberry'),
	('limoncello'),
	('liqueur'),
	('liquorice'),
	('livelong'),
	('liverpool tart'),
	('llama'),
	('lobelia'),
	('lobster'),
	('loganberry'),
	('loins'),
	('lollipop'),
	('longan'),
	('loquat'),
	('lotus'),
	('lungwort'),
	('lupin bean'),
	('lychee'),
	('m&m’s'),
	('mac&cheese'),
	('maca'),
	('macadamia'),
	('macaroon'),
	('mace'),
	('madeleine'),
	('magdalena'),
	('maize'),
	('malabar'),
	('mallow'),
	('malted milk'),
	('malvern pudding'),
	('manchurian rice'),
	('mandarin'),
	('mandelbrodt'),
	('mango'),
	('maquiberry'),
	('marijuana'),
	('marjoram'),
	('marmalade'),
	('marmite'),
	('marron glacé'),
	('marrow'),
	('marshmallow'),
	('marzipan'),
	('masala'),
	('mash'),
	('matzah ball'),
	('mayapple'),
	('meat pie'),
	('meat'),
	('melba toast'),
	('melon'),
	('meringue'),
	('mesquite'),
	('miche'),
	('milk bottles'),
	('milk chocolate'),
	('milk powder'),
	('milk'),
	('mille-feuille'),
	('millet'),
	('milo'),
	('mincemeat'),
	('mint'),
	('miso'),
	('mistletoe'),
	('mochi'),
	('mock duck'),
	('molass'),
	('monkey'),
	('mooncake'),
	('moose'),
	('mora de castilla'),
	('moth bean'),
	('mozzarella'),
	('muesli'),
	('muffin'),
	('mugwort'),
	('mulberry'),
	('mulled wine'),
	('mung bean'),
	('munggo'),
	('munster'),
	('muscadine'),
	('muscat'),
	('mushroom'),
	('mushy peas'),
	('mussels'),
	('mustard'),
	('mutton'),
	('naan'),
	('nachos'),
	('nannyberry'),
	('nectarine'),
	('neem'),
	('nesquik'),
	('nettle'),
	('nice'),
	('nièr butter'),
	('nipplewort'),
	('noodle'),
	('noodles'),
	('nugget'),
	('nut butter'),
	('nut roast'),
	('nut'),
	('nutella'),
	('nutmeg'),
	('oat milk'),
	('oatmeal'),
	('octopus'),
	('okra'),
	('olive'),
	('omelette'),
	('onigiri'),
	('onion ring'),
	('onion soup'),
	('onion'),
	('oolong'),
	('opera'),
	('orache'),
	('orange juice'),
	('orange'),
	('oregano'),
	('oreo'),
	('orzo'),
	('ostrich'),
	('oxo'),
	('oysetr'),
	('oyster'),
	('ozark pudding'),
	('paciencia'),
	('pain au chocolat'),
	('pain aux raisins'),
	('pain d’épices'),
	('pain perdu'),
	('pak choy'),
	('palestinian sweet lime'),
	('palmheart'),
	('pan de coco'),
	('pancake'),
	('pandan'),
	('pandoro'),
	('paneer'),
	('panelle'),
	('panettone'),
	('panna cotta'),
	('pansotti'),
	('papaya'),
	('paprika'),
	('paracress'),
	('parfait'),
	('paris-brest'),
	('parkia'),
	('parsley'),
	('parsnip'),
	('partridge'),
	('passionfruit'),
	('pasta'),
	('pastie'),
	('pastrami'),
	('pastry'),
	('pasty'),
	('patchouli'),
	('pâte de fruit'),
	('pâté'),
	('pattice'),
	('pattypan'),
	('pavlova'),
	('pawpaw'),
	('pea'),
	('peabutter'),
	('peach'),
	('peanut butter'),
	('peanut'),
	('pear'),
	('pease pudding'),
	('pecan'),
	('pectin'),
	('penne'),
	('pennyroyal'),
	('pepper'),
	('peppermint'),
	('perdix'),
	('peri-peri'),
	('persimmon'),
	('pesto'),
	('pez'),
	('pheasant'),
	('pie floater'),
	('pie'),
	('pig'),
	('pigeon'),
	('piglet'),
	('pignut'),
	('pili'),
	('pine nut'),
	('pineapple'),
	('pink chocolate'),
	('pinto'),
	('pipi'),
	('pistachio'),
	('pitaya'),
	('pizza'),
	('plantain'),
	('plum pine'),
	('plum tomato'),
	('plum'),
	('poached egg'),
	('pochas'),
	('pocky'),
	('pog'),
	('pōhue'),
	('poire belle hélène'),
	('poke'),
	('polenta'),
	('pomegranate'),
	('pomelo'),
	('pomodorino'),
	('popcorn'),
	('poppy'),
	('porcupine'),
	('pork'),
	('porridge'),
	('posset'),
	('possum'),
	('postum'),
	('potato bread'),
	('potato'),
	('poutine'),
	('prawn'),
	('prawns'),
	('preserve'),
	('pretzel'),
	('prickly pear'),
	('prosopis'),
	('protein bar'),
	('prune'),
	('pudding'),
	('puffin'),
	('pukeko'),
	('pullapart'),
	('pulse'),
	('pumpkin'),
	('punch'),
	('purse'),
	('purslane'),
	('purtumute'),
	('quail'),
	('quaker oats'),
	('quassia'),
	('quiche'),
	('quinoa'),
	('rabbit'),
	('radish'),
	('ragleaf'),
	('raisin'),
	('rambutan'),
	('raspberry'),
	('rattlesnake'),
	('raviole'),
	('ravioli'),
	('reblochon'),
	('red bean'),
	('red deer'),
	('red kuri'),
	('reindeer milk'),
	('reindeer'),
	('relish'),
	('remoudou'),
	('remoulade'),
	('rhubarb'),
	('rice milk'),
	('rice'),
	('ricebean'),
	('ricotta'),
	('rillettes'),
	('rimu'),
	('rind'),
	('roast'),
	('rock cake'),
	('rocket'),
	('roll'),
	('romaine'),
	('rooibos'),
	('roquefort'),
	('rose hips'),
	('rosemary'),
	('roti'),
	('rüdesheimer kaffee'),
	('rue'),
	('rusk'),
	('rutabaga'),
	('rye bread'),
	('s’mores'),
	('safflower'),
	('saffron'),
	('sagada orange'),
	('sage'),
	('sagebrush'),
	('sake'),
	('sakura cheese'),
	('salad'),
	('salmon'),
	('salmonberry'),
	('salt'),
	('salvia'),
	('samosa'),
	('samphire'),
	('sandwich'),
	('sarrasin'),
	('sassafras'),
	('sauce vierge'),
	('sauce'),
	('sauerkraut'),
	('sausage'),
	('savin'),
	('savory'),
	('savoy'),
	('scallion'),
	('scone'),
	('scorzonera'),
	('scotch bonnet'),
	('scrambled eggs'),
	('sculpit'),
	('sea kale'),
	('seafood'),
	('seaweed'),
	('seed'),
	('semolina'),
	('sencha'),
	('senna tora'),
	('sesame seed'),
	('sesame'),
	('shaker pie'),
	('shallot'),
	('shawarma'),
	('sheep milk'),
	('sherbet'),
	('shiitake'),
	('shiro'),
	('shiso'),
	('shortbread'),
	('shortcake'),
	('shrimp'),
	('silphium'),
	('sirop de liège'),
	('sirop'),
	('skullcap'),
	('sloe'),
	('smoked cheese'),
	('smoothie'),
	('snack'),
	('snails'),
	('snake'),
	('snap pea'),
	('snow pea'),
	('snowberry'),
	('soda bread'),
	('soda'),
	('soft serve'),
	('soko sorrel'),
	('sorana'),
	('sorbet'),
	('sorghum'),
	('sorrel'),
	('soufflé'),
	('soup'),
	('sour cream'),
	('sour'),
	('sourdough'),
	('sowthistle'),
	('soy milk'),
	('soy'),
	('soylent'),
	('space cakes'),
	('spaghetti squash'),
	('spam'),
	('spearmint'),
	('speculoos'),
	('spelt'),
	('spikenard'),
	('spinach'),
	('split pea'),
	('sponge cake'),
	('spotted dick'),
	('spread'),
	('spring onion'),
	('spring roll'),
	('springbok'),
	('spruce'),
	('squash'),
	('squid'),
	('squirrel'),
	('st. john’s wort'),
	('star fruit'),
	('stevia'),
	('stew'),
	('stirfry'),
	('strawberry'),
	('string cheese'),
	('striped bass'),
	('stroopwafel'),
	('strudel'),
	('stuffed eggplant'),
	('stuffed tomatoes'),
	('sturgean'),
	('sub'),
	('sugarcane'),
	('sugarloaf'),
	('sultana'),
	('sumac'),
	('summer roll'),
	('sundae'),
	('surimi'),
	('sushi'),
	('sussex pond pudding'),
	('swede'),
	('sweet piquanté'),
	('sweet potato'),
	('swiss cheese'),
	('swiss roll'),
	('szechuan pepper'),
	('tabasco'),
	('tabbouleh'),
	('taco soup'),
	('taffy'),
	('tagliatelle'),
	('tahini'),
	('tahr'),
	('tamarillo tayberry'),
	('tamarind'),
	('tangelo'),
	('tangerine'),
	('tansy'),
	('tapas'),
	('tapioca'),
	('taro'),
	('tarragon'),
	('tart'),
	('tartar'),
	('tarte des alpes'),
	('tarte tatin'),
	('tatsoi'),
	('tea'),
	('teff'),
	('teurgoule'),
	('texas caviar'),
	('thimbleberry'),
	('thistle'),
	('thyme'),
	('ti'),
	('tigernut'),
	('tikka'),
	('tilapia'),
	('tiramisu'),
	('toffee'),
	('tofu'),
	('tomatillo'),
	('tomato caviar'),
	('tomato jam'),
	('tomato juice'),
	('tomato soup'),
	('tomato'),
	('tongue'),
	('torte'),
	('tortellini'),
	('tortelloni'),
	('totara'),
	('trappista'),
	('treacle tart'),
	('trifle'),
	('tripe'),
	('triticale'),
	('troika'),
	('tromboncino'),
	('trout'),
	('truffle'),
	('tuile'),
	('tulsi'),
	('turducken'),
	('turkey'),
	('turkish delight'),
	('turmeric'),
	('turnip'),
	('turnover'),
	('turtle bean'),
	('turtle'),
	('urdă'),
	('vache qui rit'),
	('vampire pumpkin'),
	('vanilla'),
	('veal'),
	('vegemite'),
	('vegetarian chili'),
	('velvet'),
	('venison'),
	('vermicelli'),
	('vervain'),
	('vienna'),
	('viennoiserie'),
	('vinegar'),
	('voatsiperifery'),
	('wafer'),
	('waffle'),
	('walnut'),
	('wasabi'),
	('water buffalo'),
	('water chestnut'),
	('water'),
	('watercress'),
	('waterfowl'),
	('watermelon'),
	('wattleseed'),
	('wedges'),
	('weetabix'),
	('welsh rarebit'),
	('whale'),
	('wheat'),
	('wheatgrass'),
	('whey'),
	('whipped cream'),
	('white chocolate'),
	('white tea'),
	('white-tailed deer'),
	('wildebeest'),
	('willow'),
	('wine'),
	('winter squash'),
	('wolfberry'),
	('woodcock'),
	('woodruff'),
	('worm'),
	('wormseed'),
	('wrap'),
	('yacón'),
	('yak butter'),
	('yak milk'),
	('yak'),
	('yam'),
	('yarrow'),
	('yellow tea'),
	('yogurt'),
	('youngberry'),
	('yule log'),
	('zebra'),
	('zigzag vine fruit'),
	('ziti'),
	('zucchini')
;
