CREATE TABLE `pick_cards` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`text` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `text uniq` (`text`)
);

INSERT INTO `pick_cards` (`text`) VALUES
	('ace of spades'),
	('one of spades'),
	('two of spades'),
	('three of spades'),
	('four of spades'),
	('five of spades'),
	('six of spades'),
	('seven of spades'),
	('eight of spades'),
	('nine of spades'),
	('ten of spades'),
	('jack of spades'),
	('page of spades'),
	('knight of spades'),
	('queen of spades'),
	('king of spades'),

	('ace of clubs'),
	('one of clubs'),
	('two of clubs'),
	('three of clubs'),
	('four of clubs'),
	('five of clubs'),
	('six of clubs'),
	('seven of clubs'),
	('eight of clubs'),
	('nine of clubs'),
	('ten of clubs'),
	('jack of clubs'),
	('page of clubs'),
	('knight of clubs'),
	('queen of clubs'),
	('king of clubs'),

	('ace of diamonds'),
	('one of diamonds'),
	('two of diamonds'),
	('three of diamonds'),
	('four of diamonds'),
	('five of diamonds'),
	('six of diamonds'),
	('seven of diamonds'),
	('eight of diamonds'),
	('nine of diamonds'),
	('ten of diamonds'),
	('jack of diamonds'),
	('page of diamonds'),
	('knight of diamonds'),
	('queen of diamonds'),
	('king of diamonds'),

	('ace of hearts'),
	('one of hearts'),
	('two of hearts'),
	('three of hearts'),
	('four of hearts'),
	('five of hearts'),
	('six of hearts'),
	('seven of hearts'),
	('eight of hearts'),
	('nine of hearts'),
	('ten of hearts'),
	('jack of hearts'),
	('page of hearts'),
	('knight of hearts'),
	('queen of hearts'),
	('king of hearts'),

	('one of honours'),
	('two of honours'),
	('three of honours'),
	('four of honours'),
	('five of honours'),
	('six of honours'),
	('seven of honours'),
	('eight of honours'),
	('nine of honours'),
	('ten of honours'),
	('eleven of honours'),
	('twelve of honours'),
	('thirteen of honours'),
	('fourteen of honours'),
	('fifteen of honours'),
	('sixteen of honours'),
	('seventeen of honours'),
	('eighteen of honours'),
	('nineteen of honours'),
	('twenty of honours'),
	('twenty-one of honours'),

	('the little'),
	('the fool'),

	('joker'),

	('the magician'),
	('the high priestess'),
	('the empress'),
	('the emperor'),
	('the hierophant'),
	('the lovers'),
	('the chariot'),
	('strength'),
	('the hermit'),
	('wheel of fortune'),
	('justice'),
	('the hanged man'),
	('death'),
	('temperance'),
	('the devil'),
	('the tower'),
	('the star'),
	('the moon'),
	('the sun'),
	('judgement'),
	('the world'),

	('hope'),
	('prudence'),
	('faith'),
	('charity'),
	('fire'),
	('earth'),
	('water'),
	('air'),

	('ace of swords'),
	('one of swords'),
	('two of swords'),
	('three of swords'),
	('four of swords'),
	('five of swords'),
	('six of swords'),
	('seven of swords'),
	('eight of swords'),
	('nine of swords'),
	('ten of swords'),
	('jack of swords'),
	('page of swords'),
	('knight of swords'),
	('queen of swords'),
	('king of swords'),

	('ace of batons'),
	('one of batons'),
	('two of batons'),
	('three of batons'),
	('four of batons'),
	('five of batons'),
	('six of batons'),
	('seven of batons'),
	('eight of batons'),
	('nine of batons'),
	('ten of batons'),
	('jack of batons'),
	('page of batons'),
	('knight of batons'),
	('queen of batons'),
	('king of batons'),

	('ace of coins'),
	('one of coins'),
	('two of coins'),
	('three of coins'),
	('four of coins'),
	('five of coins'),
	('six of coins'),
	('seven of coins'),
	('eight of coins'),
	('nine of coins'),
	('ten of coins'),
	('jack of coins'),
	('page of coins'),
	('knight of coins'),
	('queen of coins'),
	('king of coins'),

	('ace of cups'),
	('one of cups'),
	('two of cups'),
	('three of cups'),
	('four of cups'),
	('five of cups'),
	('six of cups'),
	('seven of cups'),
	('eight of cups'),
	('nine of cups'),
	('ten of cups'),
	('jack of cups'),
	('page of cups'),
	('knight of cups'),
	('queen of cups'),
	('king of cups'),

	('ace of wands'),
	('one of wands'),
	('two of wands'),
	('three of wands'),
	('four of wands'),
	('five of wands'),
	('six of wands'),
	('seven of wands'),
	('eight of wands'),
	('nine of wands'),
	('ten of wands'),
	('jack of wands'),
	('page of wands'),
	('knight of wands'),
	('queen of wands'),
	('king of wands'),

	('ace of rods'),
	('one of rods'),
	('two of rods'),
	('three of rods'),
	('four of rods'),
	('five of rods'),
	('six of rods'),
	('seven of rods'),
	('eight of rods'),
	('nine of rods'),
	('ten of rods'),
	('jack of rods'),
	('page of rods'),
	('knight of rods'),
	('queen of rods'),
	('king of rods'),

	('ace of staves'),
	('one of staves'),
	('two of staves'),
	('three of staves'),
	('four of staves'),
	('five of staves'),
	('six of staves'),
	('seven of staves'),
	('eight of staves'),
	('nine of staves'),
	('ten of staves'),
	('jack of staves'),
	('page of staves'),
	('knight of staves'),
	('queen of staves'),
	('king of staves'),

	('ace of discs'),
	('one of discs'),
	('two of discs'),
	('three of discs'),
	('four of discs'),
	('five of discs'),
	('six of discs'),
	('seven of discs'),
	('eight of discs'),
	('nine of discs'),
	('ten of discs'),
	('jack of discs'),
	('page of discs'),
	('knight of discs'),
	('queen of discs'),
	('king of discs'),

	('ace of pentacles'),
	('one of pentacles'),
	('two of pentacles'),
	('three of pentacles'),
	('four of pentacles'),
	('five of pentacles'),
	('six of pentacles'),
	('seven of pentacles'),
	('eight of pentacles'),
	('nine of pentacles'),
	('ten of pentacles'),
	('jack of pentacles'),
	('page of pentacles'),
	('knight of pentacles'),
	('queen of pentacles'),
	('king of pentacles')
;
