CREATE TABLE `pick_gemstones` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`text` VARCHAR(255) NOT NULL,
	`colour` VARCHAR(255),
	PRIMARY KEY (`id`),
	UNIQUE KEY `text uniq` (`text`)
);

INSERT INTO `pick_gemstones` (`text`, `colour`) VALUES
	('achroite', null),
	('actinolite', 'green'),
	('adamite', 'green'),
	('adularia', null),
	('aegerine', 'green'),
	('afghanite', 'blue'),
	('agate', null),
	('agrellite', 'pink'),
	('albite', null),
	('alexandrite', null),
	('almandine', null),
	('alunite', 'yellow'),
	('amazonite', null),
	('amber', null),
	('amblygonite', 'white'),
	('amethyst', null),
	('ametrine', null),
	('ammolite', null),
	('analcime', 'white'),
	('analcite', 'white'),
	('anatase', 'black'),
	('andalusite', 'pink'),
	('andesine', 'white'),
	('andradite', null),
	('anglesite', 'clear'),
	('anhydrite', 'white'),
	('annabergite', 'green'),
	('anorthite', null),
	('anorthoclase', null),
	('antigorite', 'green'),
	('anyolite', null),
	('apache tears', null),
	('apatite', 'green'),
	('apophyllite', 'white'),
	('aquamarine', 'blue'),
	('aragonite', 'white'),
	('arfvedsonite', 'black'),
	('astrophyllite', null),
	('atacamite', 'green'),
	('austinite', 'yellow'),
	('axinite', 'brown'),
	('azurite', 'blue'),
	('azurmalachite', 'blue'),
	('baryte', 'white'),
	('bastnäsite', 'yellow'),
	('bastnaesite', 'yellow'),
	('bauxite', null),
	('bayldonite', 'green'),
	('benitoite', 'blue'),
	('beryl', 'clear'),
	('beryllium', 'gray'),
	('beryllonite', 'white'),
	('beudantite', 'black'),
	('biotite', 'brown'),
	('bloodstone', 'red'),
	('boleite', 'blue'),
	('bone', 'white'),
	('boracite', 'green'),
	('bornite', 'red'),
	('bort', 'yellow'),
	('bowenite', 'green'),
	('brazilianite', 'yellow'),
	('bronzite', null),
	('brookite', 'red'),
	('brucite', 'green'),
	('bustamite', 'pink'),
	('bytownite', 'clear'),
	('calcite', 'white'),
	('caledonite', 'green'),
	('californite', null),
	('cancrinite', 'white'),
	('carletonite', 'blue'),
	('carnallite', 'clear'),
	('carnelian', 'red'),
	('cassiterite', 'black'),
	('castorite', null),
	('cavansite', 'blue'),
	('celestine', 'clear'),
	('celestite', 'clear'),
	('celsian', null),
	('cerussite', 'white'),
	('ceylonite', null),
	('chabazite', 'pink'),
	('chalcedony', null),
	('chalcopyrite', 'yellow'),
	('chambersite', 'purple'),
	('charlesite', 'white'),
	('charoite', 'violet'),
	('chiastolite', null),
	('lapis crucifer', null),
	('lapis cruciatur', null),
	('childrenite', null),
	('chlorastrolite', null),
	('chloromelanite', null),
	('chondrodite', null),
	('chrome', null),
	('chrome chalcedony', null),
	('chromite', null),
	('chrysoberyl', null),
	('chrysocolla', null),
	('chrysoprase', null),
	('chrysotile', null),
	('cinnabar', null),
	('citrine', null),
	('clinochlore', null),
	('clinohumite', null),
	('clinozoisite', null),
	('clintonite', null),
	('copal', null),
	('coral', null),
	('cordierite', null),
	('cornwallite', null),
	('corundum', null),
	('covellite', null),
	('creedite', null),
	('crocidolite', null),
	('cryolite', null),
	('cubic zirconia', null),
	('cuprite', null),
	('cymophane', null),
	('danburite', null),
	('datolite', null),
	('demantoid', null),
	('dendritic agate', null),
	('descloizite', null),
	('diamond', null),
	('diaspore', null),
	('diopside', null),
	('dioptase', null),
	('dolomite', null),
	('dravite', null),
	('druzy', null),
	('dumortierite', null),
	('eilat stone', null),
	('elbaite', null),
	('emerald', null),
	('enstatite', null),
	('eosphorite', null),
	('epidosite', null),
	('epidote', null),
	('erythrite', null),
	('esperite', null),
	('ettringite', null),
	('euclase', null),
	('eudialyte', null),
	('fayalite', null),
	('feldspar', null),
	('ferroaxinite', null),
	('fire agate', null),
	('flint', null),
	('fluor-liddicoatite', null),
	('fluorapatite', null),
	('fluorapophyllite', null),
	('fluorite', null),
	('fordite', null),
	('forsterite', null),
	('fuchsite', null),
	('gahnite', null),
	('garnet', null),
	('gaspeite', null),
	('gaylussite', null),
	('gibbsite', null),
	('glaucophane', null),
	('goethite', null),
	('golden beryl', null),
	('goosecreekite', null),
	('goshenite', 'clear'),
	('grandidierite', null),
	('grandite', null),
	('grossular ugrandite', null),
	('gypsum', null),
	('gyrolite', null),
	('hackmanite', null),
	('halite', null),
	('hambergite', null),
	('hanksite', null),
	('hardystonite', null),
	('hauyne', null),
	('hawk’s eye', null),
	('helenite', null),
	('heliodor', null),
	('heliotrope', null),
	('hematite', null),
	('hemimorphite', null),
	('herderite', null),
	('hessonite', null),
	('hexagonite', null),
	('hibonite', null),
	('hiddenite', null),
	('hodgkinsonite', null),
	('howlite', null),
	('humite', null),
	('hydrogrossular', null),
	('hypersthene', null),
	('iddingsite', null),
	('idocrase', null),
	('indicolite', null),
	('iolite', null),
	('iris agate', null),
	('jacinth', null),
	('jade', null),
	('jadeite', null),
	('jasper', null),
	('jeremejevite', null),
	('jet', null),
	('kainite', null),
	('kornerupine', null),
	('kunzite', null),
	('kurnakovite', null),
	('kutnohorite', null),
	('kyanite', null),
	('lab alexandrite', null),
	('lab corundum', null),
	('lab diamond', null),
	('lab emerald', null),
	('lab moissanite', null),
	('lab spinel', null),
	('labradorite', null),
	('langbeinite', null),
	('lapis lazuli', null),
	('larimar', null),
	('lawsonite', null),
	('lazurite', null),
	('legrandite', null),
	('lepidolite', null),
	('leucite', null),
	('leucophanite', null),
	('libyan desert glass', null),
	('linarite', null),
	('lizardite', null),
	('llanite', null),
	('londonite', null),
	('ludlamite', null),
	('magnesioaxinite', null),
	('magnesite', null),
	('malachite', null),
	('malaia garnet', null),
	('mali garnet', null),
	('manganaxinite', null),
	('manganocalcite', null),
	('marialite', null),
	('maw sit sit', null),
	('meionite', null),
	('melanite', null),
	('metal-coated crystals hyped as rainbow quartz', null),
	('microcline', null),
	('milky quartz', null),
	('mimetite', null),
	('moissanite', null),
	('moldavite', null),
	('moonstone', null),
	('morganite', 'pink'),
	('moss agate', null),
	('mother of pearl', null),
	('mottramite', null),
	('muscovite', null),
	('musgravite', null),
	('nacre', null),
	('narsarsukite', null),
	('natrolite', null),
	('nepheline', null),
	('nephrite', null),
	('neptunite', null),
	('nickeline', null),
	('nuummite', null),
	('obsidian', null),
	('olenite', null),
	('olivine', null),
	('olivinite', null),
	('onyx', null),
	('opal', null),
	('operculum', null),
	('orthoclase', null),
	('padparadscha', null),
	('painite', null),
	('pallasite', null),
	('papagoite', null),
	('paraiba', null),
	('pargasite', null),
	('pearl', null),
	('pectolite', null),
	('periclase', null),
	('peridot', null),
	('peridotite', null),
	('peristerite', null),
	('petalite', null),
	('petrified wood', null),
	('pezzottaite', null),
	('phenakite', null),
	('phlogopite', null),
	('phosgenite', null),
	('phosphophyllite', null),
	('phosphosiderite', null),
	('piemontite', null),
	('pietersite', null),
	('plumbogummite', null),
	('pollucite', null),
	('polyhalite', null),
	('poudretteite', null),
	('prasiolite', null),
	('prehnite', null),
	('prismatine', null),
	('proustite', null),
	('pumpellyite', null),
	('purpurite', null),
	('pyralspite', null),
	('pyrargyrite', null),
	('pyrite', null),
	('pyromorphite', null),
	('pyrope', null),
	('pyrrhotite', null),
	('quartz', null),
	('radiolarite', null),
	('rainbow moonstone', null),
	('red beryl', null),
	('rhodizite', null),
	('rhodochrosite', null),
	('rhodolite', null),
	('richterite', null),
	('riebeckite', null),
	('rock crystal', null),
	('rosasite', null),
	('rose quartz', null),
	('rossmanite', null),
	('rubellite', null),
	('ruby', null),
	('rutile', null),
	('sanidine', null),
	('sapphire', null),
	('sard', null),
	('sardonyx', null),
	('scapolite', null),
	('scheelite', null),
	('schizolite', null),
	('scolecite', null),
	('scorodite', null),
	('selenite', null),
	('sellaite', null),
	('senarmontite', null),
	('seraphinite', null),
	('serendibite', null),
	('serpentine', null),
	('shattuckite', null),
	('shigaite', null),
	('shortite', null),
	('shungite', null),
	('siderite', null),
	('sillimanite', null),
	('sinhalite', null),
	('smithsonite', null),
	('smoky quartz', null),
	('soapstone', null),
	('sodalite', null),
	('sperrylite', null),
	('spessartine', null),
	('spessartite', null),
	('sphene', null),
	('spinel', null),
	('spodumene', null),
	('staurolite', null),
	('steatite', null),
	('stellerite', null),
	('stichtite', null),
	('stolzite', null),
	('sugilite', null),
	('sulfur', null),
	('sunstone', null),
	('sylvite', null),
	('synthetic opal', null),
	('synthetic turquoise', null),
	('sérandite', null),
	('taaffeite', null),
	('tactite', null),
	('tantalite', null),
	('tanzanite', null),
	('thaumasite', null),
	('thomsonite', null),
	('thulite', null),
	('tiger’s eye', null),
	('tinaksite', null),
	('tinzenite', null),
	('titanite', null),
	('topaz', null),
	('topazolite', null),
	('tourmaline', null),
	('trapiche emerald', null),
	('tremolite', null),
	('trinitite', null),
	('triphane', null),
	('tsavorite', null),
	('tugtupite', null),
	('turquoise', null),
	('ugrandite', null),
	('ulexite', null),
	('umbalite', null),
	('unakite', null),
	('uvarovite', null),
	('vanadinite', null),
	('variscite', null),
	('vesuvianite', null),
	('villiaumite', null),
	('vishnevite', 'clear'),
	('vlasovite', null),
	('väyrynenite', null),
	('wavellite', null),
	('weloganite', null),
	('wernerite', null),
	('willemite', null),
	('wulfenite', null),
	('xonotlite', null),
	('yttrium aluminium garnet', null),
	('zektzerite', null),
	('zeolites', null),
	('zincite', null),
	('zinnwaldite', null),
	('zircon', null),
	('zoisite', null)
;

CREATE INDEX `colour` ON `pick_gemstones` (`colour`);
