FROM ruby:alpine AS doc

WORKDIR /build

COPY static /build/static
COPY app /build/app
COPY bin /build/bin

RUN apk add bash
RUN bin/build-help


FROM nginx:alpine

WORKDIR /webroot

COPY --from=doc /build/static /webroot/static
COPY app /webroot/app

COPY prod/nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/garrire.conf

ENTRYPOINT ["sh", "-c"]
CMD ["exec nginx"]
