FROM rust:alpine AS build

RUN apk add git build-base openssl-dev
RUN git clone https://github.com/passcod/accord /build

WORKDIR /build
RUN git checkout v0.0.3
RUN cargo build --release
RUN strip target/release/accord


FROM alpine

COPY --from=build /build/target/release/accord /bin/
CMD ["/bin/accord"]
