<?php

/// colour (color) - Get a random colour.

namespace App\Controllers\Command;

class Colour extends \App\Controller
{
  const COLOURS = [
    'silver',
    'gray',
    'white',
    'maroon',
    'red',
    'purple',
    'fuchsia',
    'green',
    'lime',
    'olive',
    'yellow',
    'navy',
    'blue',
    'teal',
    'aqua',
    'antique white',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'blanched almond',
    'blue violet',
    'brown',
    'burlywood',
    'cadet blue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflower blue',
    'cornsilk',
    'crimson',
    'cyan',
    'aqua',
    'dark blue',
    'dark green',
    'dark grey',
    'dark khaki',
    'dark magenta',
    'dark orange',
    'dark red',
    'dark slate',
    'dark turquoise',
    'dark violet',
    'dark purple',
    'dark yellow',
    'deep pink',
    'hot pink',
    'deepsky blue',
    'dimgrey',
    'dodger blue',
    'firebrick',
    'floral white',
    'forest green',
    'gainsboro',
    'ghost white',
    'gold',
    'goldenrod',
    'green yellow',
    'yellow green',
    'grey',
    'honeydew',
    'hotpink',
    'indian red',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavender blush',
    'lawn green',
    'lemon chiffon',
    'light blue',
    'light green',
    'light grey',
    'light pink',
    'light red',
    'light brown',
    'light yellow',
    'lime green',
    'linen',
    'magenta',
    'fuchsia',
    'midnight blue',
    'mint cream',
    'misty rose',
    'moccasin',
    'navajo white',
    'old lace',
    'olive drab',
    'orange red',
    'orchid',
    'pale goldenrod',
    'pale green',
    'pale turquoise',
    'pale violet red',
    'papaya whip',
    'peach puff',
    'peru',
    'pink',
    'plum',
    'powder blue',
    'rosy brown',
    'royal blue',
    'saddle brown',
    'salmon',
    'sandy brown',
    'seagreen',
    'seashell',
    'sienna',
    'sky blue',
    'slate blue',
    'slate grey',
    'snow',
    'spring green',
    'steel blue',
    'tan',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'whitesmoke',
    'yellowgreen',
    'rebecca purple',
    'orange',
    'aqua',
    'black',
  ];

  public function post(): void
  {
    $this->help();
    if (empty($this->argument())) $this->show_help();

    $this->reply(static::COLOURS[array_rand(static::COLOURS)], null, true);
  }
}
